version: '3.3'

services:
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./wordpress:/var/www/html
      - ./wordpress/wp-content/plugins
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
#     - ./apache-entrypoint.sh:/usr/local/bin/apache-entrypoint.sh
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: lauti
      WORDPRESS_DB_PASSWORD: lauti
      WORDPRESS_DEBUG: 1
#    entrypoint: /usr/local/bin/apache-entrypoint.sh

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./db/:/docker-entrypoint-initdb.d/
    command: --max_allowed_packet=32505856      # Set max_allowed_packet to 256M (or any other value)
    environment:
      MYSQL_ROOT_PASSWORD: my_db_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: lauti
      MYSQL_PASSWORD: lauti

  cli:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    # user-id as wordpress. This way there are no permission problems
    # when running the cli
    user: xfs
    volumes:
      - ./wordpress:/var/www/html

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
    ports:
      - '8080:80'
volumes:
  db_data:
